### ISSUE TITLE
Add a pre-commit hook which ensures `uv.lock` is up to date

### ISSUE THREAD

**Issue by nathanjmcdougall** [nathanjmcdougall/usethis-python#117]
**Motivation**
It's possible to de-sync with the lockfile if we don't have a pre-commit check for this.
As a pre-commit hook it can be fixed automatically and also we can check it on CI.

Should look at https://github.com/astral-sh/uv-pre-commit to see if there's a satisfactory solution

**Summary of desired enhancement**
Ability to check the lockfile is up-to-date in CI and pre-commit.

**Comment by nathanjmcdougall** [comment]
Easy:

```YAML
- repo: https://github.com/astral-sh/uv-pre-commit
  # uv version.
  rev: 0.5.2
  hooks:
    # Update the uv lockfile
    - id: uv-lock
```
