### ISSUE TITLE
Something to opt into requirements.txt

### ISSUE THREAD

**Issue by nathanjmcdougall** [nathanjmcdougall/usethis-python#144]
**Motivation**
There are some applications where `requirements.txt` files are the expected file format, mostly in cloud deployments. For example, see
https://discuss.python.org/t/pep-751-now-with-graphs/69721/193

It's not ideal to have both requirements.txt and uv.lock but it can be unavoidable, so there should be a mechanism to generate the former from the latter. I think that's basically provided via `uv export` but there's a uv-pre-commit hook to do it too and there's some subtlety so I think it could be good to support it.

**Summary of desired enhancement**
Provide a way to generate `requirements.txt` files. The focus would only be on deployment so only the core requirements, no optional requirements or extras would be included.

**Comment by nathanjmcdougall** [comment]
Here is the expected config:

```YAML
  - repo: local
    hooks:
      - id: uv-export
        name: uv-export
        files: ^uv\.lock$
        pass_filenames: false
        entry: uv export --frozen --no-dev --output-file=requirements.txt --quiet
        language: system
        require_serial: true
```
