### ISSUE TITLE
Implement `usethis tool codespell`

### ISSUE THREAD

**Issue by nathanjmcdougall** [nathanjmcdougall/usethis-python#271]
**Motivation**
See #270 and #261 - this tool works really well and is simple enough to configure.

**Summary of desired enhancement**
Implement `codespell` as a supported tool. It has pre-commit integration but by default no pyproject.toml is necessary (although I think a blank ignored words list would be sensible)

```TOML
[tool.codespell]
ignore-words-list = [ ]
```
