### ISSUE TITLE
Add some basic pre-commit hooks suggested by `sp-repo-review`

### ISSUE THREAD

**Issue by nathanjmcdougall** [nathanjmcdougall/usethis-python#367]
**Motivation**
Suggested via #349 

e.g.

```YAML
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-yaml
      - id: debug-statements
      - id: name-tests-test
        args: ["--pytest-test-first"]
```

**Summary of desired enhancement**
Enable these pre-commit checks for dev.
