### ISSUE TITLE
Improve `pytest` configuration

### ISSUE THREAD

**Issue by nathanjmcdougall** [nathanjmcdougall/usethis-python#371]
**Motivation**
Some good ideas suggested via #349

```TOML
[tool.pytest.ini_options]
xfail_strict = true
log_cli_level = "INFO"
minversion = "7"
testpaths = [ "tests" ]
addopts = [
  "--import-mode=importlib",
  "-ra",
  "--strict-config",
  "--strict-markers",
]
filterwarnings = [ "error" ]
```

**Summary of desired enhancement**
Enable this improved config by default for development, and add it via `usethis tool pytest` (or at least consider the ramifications of doing this).
