### ISSUE TITLE
coverage config created is invalid

### ISSUE THREAD

**Issue by grantps** [nathanjmcdougall/usethis-python#426]
**Motivation**
```TOML
[tool.coverage.run]
source = ["src"]
```
This is what I get in `pyproject.toml` but when running `pytest --cov` I get this error:

```
coverage.exceptions.ConfigError: Couldn't read config file pyproject.toml: Option [tool.coverage.run]source is not a list: 'src'
```

**Summary of desired enhancement**
Bugfix
