### ISSUE TITLE
`usethis docstyle` uses INI conventions in TOML file

### ISSUE THREAD

**Issue by nathanjmcdougall** [nathanjmcdougall/usethis-python#507]
**Motivation**
The TOML keys seem wrong:

```TOML
[tool.ruff.lint.pydocstyle]
convention = "google"
lint.ignore = [ "EM", "PLR2004", "SIM108" ]
```

**Summary of desired enhancement**
Fix and test the bug
