### ISSUE TITLE
Add project metadata to `pyproject.toml`

### ISSUE THREAD

**Issue by nathanjmcdougall** [nathanjmcdougall/usethis-python#72]
**Motivation**

The following sections are currently missing or using placeholder values in the `pyproject.toml` file.

```TOML
[project]
description = ""
authors = [
    { name = "Nathan McDougall", email = "nathan.j.mcdougall@gmail.com" },
]
license = { text = "MIT" }
classifiers = []
keywords = []

[project.urls]
"Source Code" = "https://github.com/nathanjmcdougall/usethis-python"
"Bug Tracker" = "https://github.com/nathanjmcdougall/usethis-python/issues"
```

These values should be populated before the first release on PyPI.

**Summary of desired feature**
Populate these sections with appropriate values.
